language: bash
services: docker

env:
  - VERSION=3.11
  - VERSION=3.0
  - VERSION=2.2
  - VERSION=2.1
  - VERSION=2.1.12

script: 
  - ./scripts/build.sh

deploy:
  - provider: script
    script: ./scripts/push.sh
    skip_cleanup: true 
    on:
      branch: master

branches:
  only:
    - master 
