language: bash
services: docker

env:
  - VERSION=3.11
  - VERSION=3.0
  - VERSION=2.2
  - VERSION=2.1

script: 
  - ./scripts/build.sh

deploy:
  - provider: script
    script: docker login -u $DOCKER_LOGIN -p $DOCKER_PWD && docker push gini/cassandra:${VERSION}
    on:
      branch: master

branches:
  only:
    - master 
